[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "videocut"
version = "0.1.0"
description = "Video editing pipeline driven by WhisperX transcripts"
readme = "README.md"
requires-python = ">=3.11"
authors = [{name = "VideoCut Maintainers"}]

# ✅ Only lightweight dependencies here
dependencies = [
    "click",
    "typer>=0.12",
    "ffmpeg-python",
    "python-dotenv>=1.0",
    "pdfminer.six",
    "python-dateutil",
    "torch",
    "torchaudio",
    "whisperx",
    "speechbrain",
]

[project.scripts]
videocut = "videocut.cli:main"

[tool.setuptools.packages.find]
exclude = ["videos*"]
